language: "en"
pipeline: 
- name: "rasa.nlu.featurizers.incr_count_vectors_featurizer.IncrementalCVF"
  “token_pattern”: r’(?u)\b\w+\b’
- name: "rasa.nlu.classifiers.update_incr_embedding_intent_classifier.IncrementalTF"
